---
- name: Stop PHP 7.2 starting
  shell: rm /etc/profile.d/enablephp72.sh
  ignore_errors: yes

- name: Remove PHP 7.2
  yum:
    name: php72*
    state: absent

- name: install php
  yum:
    name: php56
    state: latest
    enablerepo: remi,remi-php56

- name: install php-mbstring
  yum:
    name: php56-php-mbstring

- name: install php-mcrypt
  yum:
    name: php56-php-mcrypt

- name: install php-pdo
  yum:
    name: php56-php-pdo
    state: latest

- name: install php-mbstring
  yum:
    name: php56-php-mysqlnd
    state: latest

- name: install php-intl
  yum:
    name: php56-php-intl
    state: latest

- name: install php-bcmath
  yum:
    name: php56-php-bcmath
    state: latest

- name: install php-soap
  yum:
    name: php56-php-soap
    state: latest

- name: install php-xdebug
  yum:
    name: php56-php-pecl-xdebug
    state: latest

- name: install php-memcache
  yum:
    name: php56-php-pecl-memcache
    state: latest

- name: install php-memcached
  yum:
    name: php56-php-pecl-memcached
    state: latest

- name: install php-fpm
  yum:
    name: php56-php-fpm
    state: latest
    enablerepo: remi,remi-php56

- name: php.ini file
  template:
    src: php.ini
    dest: /opt/remi/php56/root/etc/php.ini

- name: www.cnf file
  template:
    src: www.conf
    dest: /opt/remi/php56/root/etc/php-fpm.d/www.conf

- name: create php session directory
  file:
    state: directory
    path: /var/lib/php/session
    mode: 0777

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777

- name: start php-fpm
  service:
    name: php56-php-fpm
    state: started
    enabled: true

- name: enable php56
  template:
    src: enablephp56.sh
    dest: /etc/profile.d/enablephp56.sh
