---
- name: install the epel rpm from a remote repo
  yum:
    name: epel-release
    state: latest

- name: install the remi rpm from a remote repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    state: present

- name: install the mysql 5.7 rpm from a remote repo
  yum:
    name: http://repo.mysql.com/mysql57-community-release-el6.rpm
    state: present

- name: add epel public key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6

- name: Install yum-versionlock
  yum:
    name: yum-plugin-versionlock
    state: present

- name: Add packages to versionlock
  shell: yum versionlock {{ item }}
  with_items: { versionlock_items }
  when: ({{ versionlock_items }} is defined)
