---
- name: Find PHP
  find:
    paths: /usr/bin/
    patterns: ^php[0-9]+$
    use_regex: yes
    file_type: link
  register: php_binarys

- name: PHP Version String
  shell: "{{ item.path }} -v"
  register: php_version_string
  with_items: "{{ php_binarys.files }}"
  changed_when: false
  failed_when: false

- name: Current PHP Version
  shell: "echo '{{ item.stdout }}' | grep 'PHP [0-9]\\.[0-9]' -o | grep '[0-9]\\.[0-9]' -o"
  register: current_php_version
  with_items: "{{ php_version_string.results }}"
  changed_when: false
  failed_when: false

- name: Find Enable PHP Files
  find:
    paths: /etc/profile.d/
    patterns: enablephp*
    use_regex: no
  register: start_php_files

- name: Stop Running Services
  service:
    name: "php{{ item.stdout | regex_replace('\\.', '') }}-php-fpm"
    state: stopped
    enabled: false
  when: item.stdout is defined and php_version != item.stdout
  with_items: "{{ current_php_version.results }}"

- name: Stop PHP starting
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ start_php_files.files }}"

- name: Remove PHP
  yum:
    name: php*
    state: absent
  when: item.stdout is defined and php_version != item.stdout
  with_items: "{{ current_php_version.results }}"
