---
- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Add nginx to chkconfig
  command: chkconfig --add nginx

- name: Copy nginx default configuration
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/{{ item.host_name }}.conf
  with_items: "{{ virtual_hosts }}"

- name: Auto start nginx
  command: chkconfig --levels 235 nginx on
  notify: restart nginx
